apiVersion: v1
kind: Pod
metadata:
  name: wokrker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: voting-app
    image: kodekloud/examplevotingapp_worker:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  
